version: "3.9"

services:
  postgres:
    image: postgres:12.7-alpine
    restart: always
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=portal_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=QyeRcaC8eXzC2yMatUEG
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
