import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Heading, Button } from "@chakra-ui/react";
import { useWalletContext } from "../context/wallet";

const Home: NextPage = () => {
  const walletContext = useWalletContext();

  const { address, connect, disconnect } = walletContext;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading size="2xl" mb="5">
          Welcome to Portal 🔮
        </Heading>
        {address ? (
          <div>
            <h3>{address} connected</h3>
            <Button color="white" bg="red.400" mt="10" onClick={disconnect}>
              Disconnect Wallet
            </Button>
          </div>
        ) : (
          <Button onClick={connect} style={{ margin: "1.5em" }}>
            Connect Wallet
          </Button>
        )}
      </main>
    </div>
  );
};

export default Home;
